### ISSUE TITLE
MaskRCNN

### ISSUE THREAD

**Issue by frank-wei** [mlperf/logging#17]
It looks like constants.py missed several const variables. I believe I need to add below:
    mllogger.event(key=mllog_const.**MIN_IMAGE_SIZE**, value=cfg.INPUT.MIN_SIZE_TRAIN)
    mllogger.event(key=mllog_const.**MAX_IMAGE_SIZE**, value=cfg.INPUT.MAX_SIZE_TRAIN)
    mllogger.event(key=mllog_const.EVAL_ACCURACY, value=uncased_score,
          metadata={mllog_const.**BBOX**: bbox_map, mllog_const.**SEGM**: segm_map})

**Comment by xyhuang** [comment]
+1, please feel free to create a PR:)

**Comment by frank-wei** [comment]
Sorry for the late update. Just added one PR #25
