### ISSUE TITLE
Release Candidate 2 version of the logging library

### ISSUE THREAD

**Issue by tgrel** [mlperf/logging#40]
@xyhuang what do you think about tagging this commit https://github.com/mlperf/logging/commit/4b5b4ef52fbe8b17a9e06374d884811e2264e810
as 0.7.0-rc2?

**Comment by cliffwoolley** [comment]
Note: just after we posted this issue, commit 9ea0afa was merged; so that is NVIDIA's new proposed rc2 point.  We do need to lock this down, however.

**Comment by xyhuang** [comment]
created the rc2 tag, any remaining PRs will be in rc3.
